:icons: font

= Barley Pizza Crust

WARNING: I do not recommend this recipe.

== Ingredients

* 1 cup warm water
* 1 tsp sugar
* 2 1/4 tsp quick rise yeast
* 2 T extra virgin olive oil
* 3 C barley flour
* 1/2 tsp salt

== Instructions

1. *Mix:* In a bowl, combine ingredients, reserving 1/2 barley to use in kneeding step.
2. *Knead:* On a floured surface, knead in remaining 1/2 cup of barley flour that was reserved, forming a soft dough.
3. *Rise:* Put a few drops of olive oil on dough to coat, cover, and let rise for 1 hour.
4. *Divide:* Divide dough ball into two even portions and roll out into shape for pizza crust.
5. *Pre-bake:* Bake on pizza stone in 350F oven for about 5 minutes.
6. *Top*: Top with pizza sause, toppings, and cheese.
7. *Final-bake:* Bake on pizza stone at 400F until cheese starts to brown. Check after 7 minutes. Depending on toppings, it
    could take 12-15 to complete.


== Notes

After pre-bake. Pizza crust should store well in refrigerator for a few days.

Pure barley dough makes a poor pizza crust.
